# Generated by Django 2.1.7 on 2019-06-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.CharField(default='少年', max_length=20),
        ),
    ]
