# Generated by Django 2.1.7 on 2019-07-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20190627_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfig',
            name='loginType',
            field=models.IntegerField(default=1),
        ),
    ]
