# Generated by Django 2.1.7 on 2019-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_loginconfig_logintype'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentlogin',
            name='loginType',
            field=models.IntegerField(default=1),
        ),
    ]
