# Generated by Django 2.1.7 on 2019-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20190702_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfig',
            name='checkText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='checkText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='checkText',
            field=models.TextField(null=True),
        ),
    ]
