# Generated by Django 2.1.7 on 2019-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20190719_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginconfig',
            name='selectText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='selectText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='selectText',
            field=models.TextField(null=True),
        ),
    ]
